image: shivammathur/node:jammy

variables:
  COMPOSER_ALLOW_SUPERUSER: "1"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: shopware_test

stages:
  - check
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

test:
  only:
    - merge_requests
  extends: .base
  stage: check
  parallel:
    matrix:
      - SHOPWARE_VERSION: [ "v6.5.7.3" ]
        PHP_VERSION: [ "8.1", "8.2" ]
      - SHOPWARE_VERSION: [ "v6.5.8.9" ]
        PHP_VERSION: [ "8.1", "8.2", "8.3" ]
      - SHOPWARE_VERSION: [ "v6.6.0.0", "v6.6.2.0" ]
        PHP_VERSION: ["8.2", "8.3" ]
      
  services:
    - mysql:8.0
  script:
    # Update spc (See https://github.com/shivammathur/spc for options)
    - spc -U
    
    # Setup PHP
    - spc --php-version "$PHP_VERSION"
      --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap"
    
    # Checkout Shopware production template
    - git clone --branch $SHOPWARE_VERSION https://github.com/shopware/production.git shopware
    
    # Cache composer dependencies
    - |
      dir=$(composer config cache-files-dir)
      echo "dir=$dir" >> $CI_PROJECT_DIR/.gitlab-ci-cache
    
    # Install Shopware dependencies
    - cd shopware
    - |
      composer req shopware/core:$SHOPWARE_VERSION shopware/administration:* shopware/storefront:* --no-update
      composer remove shopware/elasticsearch --no-update
    - composer install --no-progress --prefer-dist --optimize-autoloader > /dev/null
    
    # Add gitlab token to composer
    - composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN
    
    # Install clone TWINT Payment plugin to custom folder
    - git clone --branch "$CI_COMMIT_REF_NAME" "https://$GITLAB_USERNAME:$GITLAB_ACCESS_TOKEN@git.nfq.asia/twint-ag/shopware-plugin.git" custom/plugins/TwintPayment
    
    # Install TWINT plugin
    - |
      composer config prefer-stable true
      composer config minimum-stability dev
      composer config repositories.local-plugins '{ "type": "path", "url": "custom/plugins/*", "options": { "symlink": true } }'
      composer config repositories.twint-sdk vcs https://git.nfq.asia/twint-ag/php-sdk.git
    - composer require twint-ag/twint-shopware-plugin --no-progress --no-scripts > /dev/null
    
    # Install DEV-Tools
    - cd "$CI_PROJECT_DIR/shopware/custom/plugins/TwintPayment"
    - rm -f composer.lock
    - composer install --no-progress --prefer-dist --optimize-autoloader > /dev/null
    
    # Create .env file from test
    - cp .env.test .env
    - cp .env.test "$CI_PROJECT_DIR/shopware/.env"
    - DATABASE_TEST_URL="mysql://root:$MYSQL_ROOT_PASSWORD@mysql/$MYSQL_DATABASE"
    - sed -i "s|__DATABASE_URL__|$DATABASE_TEST_URL|g" "$CI_PROJECT_DIR/shopware/.env"
    
    # Run PHP Code Standard
    - ./vendor/bin/ecs --no-progress-bar
    
    # Run PHP rector
    - vendor/bin/rector process src --dry-run
    
    # Run PhpStan
    - vendor/bin/phpstan analyse -c phpstan.neon --autoload-file="$CI_PROJECT_DIR/shopware/vendor/autoload.php" src
    
    # Install Shopware to running unit test
    - cd "$CI_PROJECT_DIR/shopware"
#    - mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
    - bin/console system:install --basic-setup > /dev/null
    
    # Run unit test
    - cd custom/plugins/TwintPayment
    - composer remove shopware/core --dev
    - ./bin/phpunit.sh
  
  cache:
    key: $CI_COMMIT_REF_SLUG-${CI_JOB_NAME}
    paths:
      - $CI_PROJECT_DIR/.gitlab-ci-cache
      
end-2-end:
  only:
    - test/cypress
  stage: check
  image: cypress/browsers:latest
  tags:
    - d13-runner
  script:
    - cd cypress
    - cp cypress.env.dist.json cypress.env.json;
    - sed -i "s|\"__BASE_URL__\"|\"CYPRESS_URL\"|g" cypress.env.json
    - npm install
    - npx cypress run --headless --browser chrome
  artifacts:
    paths:
      - cypress/cypress/screenshots/
      - cypress/cypress/videos/

release:
    only:
        - tags
    stage: release
    image: alpine:3
    extends: .base
    script:
      - apk add --no-cache git openssh bash
      - ./bin/sync.sh
