image: shivammathur/node:jammy

variables:
  COMPOSER_ALLOW_SUPERUSER: "1"

stages:
  - check
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

test:
  rules:
    - if: "$CI_COMMIT_BRANCH" # runs on any branch
  extends: .base
  stage: check
  parallel:
    matrix:
      - SHOPWARE_VERSION: ["v6.5.8.9"]
        PHP_VERSION: ["8.1", "8.2", "8.3"]
      - SHOPWARE_VERSION: ["v6.6.2.0"]
        PHP_VERSION: ["8.2", "8.3"]
  script:
    # Update spc (See https://github.com/shivammathur/spc for options)
    - spc -U

    # Setup PHP
    - spc --php-version "$PHP_VERSION"
      --extensions "mbstring, curl, dom, fileinfo, gd, iconv, intl, json, xml, mbstring, pdo, phar, zip, sodium, pdo_mysql, bcmath, soap"

    # Cache composer dependencies
    - |
      dir=$(composer config cache-files-dir)
      echo "dir=$dir" >> $CI_PROJECT_DIR/.gitlab-ci-cache

    # Add gitlab token to composer
    - composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN

    - rm -f composer.lock
    - composer install --no-progress --prefer-dist --optimize-autoloader > /dev/null

    # Run PHP Code Standard
    - ./vendor/bin/ecs --no-progress-bar

    # Run PHP rector
    - vendor/bin/rector process src --dry-run

    # Run PhpStan
    - vendor/bin/phpstan analyse -c phpstan.neon src
  cache:
    key: $CI_COMMIT_REF_SLUG-${CI_JOB_NAME}
    paths:
      - $CI_PROJECT_DIR/.gitlab-ci-cache

release:
  only:
    - tags
  stage: release
  image: alpine:3
  extends: .base
  variables:
    GIT_DEPTH: 0
  script:
    - apk add --no-cache git openssh bash
    - ./bin/sync.sh
