services:
  ci66:
    container_name: ci66
    image: dockware/dev:6.6.7.0
    volumes:
      - "./../..:/builds/twint-ag/twint-shopware-plugin:rw"
      # prevent recursive binding volumes
      - "/builds/twint-ag/twint-shopware-plugin/infra"
      - "/builds/twint-ag/twint-shopware-plugin/vendor"
  ci65:
    container_name: ci65
    image: dockware/dev:6.5.8.0
    volumes:
      - "./../..:/builds/twint-ag/twint-shopware-plugin:rw"
      # prevent recursive binding volumes
      - "/builds/twint-ag/twint-shopware-plugin/infra"
      - "/builds/twint-ag/twint-shopware-plugin/vendor"
  
  ci67:
    container_name: ci67
    image: dockware/dev:6.7.2.2
    volumes:
      - "./../..:/builds/twint-ag/twint-shopware-plugin:rw"
      # prevent recursive binding volumes
      - "/builds/twint-ag/twint-shopware-plugin/infra"
      - "/builds/twint-ag/twint-shopware-plugin/vendor"
